name: .NET Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'

    - name: Build
      run: msbuild NA_Attendance_NET_Project.sln /p:Configuration=Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: NA_Attendance_App
        path: ./**/bin/Release/
